AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DBInstanceID:
    Default: gallerydbinstance
    Description: DB instance to store image metadata
    Type: String
    MinLength: '1'
    MaxLength: '63'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: >-
      Must begin with a letter and must not end with a hyphen or contain two
      consecutive hyphens.
  DBName:
    Default: gallerydb
    Description: DB to store bucket image metadata
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
  DBInstanceClass:
    Default: db.t2.micro
    Description: DB instance class
    Type: String
    ConstraintDescription: Must select a valid DB instance type.
  DBUsername:
    NoEcho: 'true'
    Description: Username for MySQL database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Description: Password MySQL database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  ASubnetCIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 10.0.13.0/24
  BSubnetCIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 10.0.23.0/24
  NetworkName:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: Bison
Resources:
  GalleryDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: 20
      DBInstanceIdentifier: !Ref DBInstanceID
      DBName: !Ref DBName
      DBInstanceClass: !Ref DBInstanceClass
      DBSubnetGroupName: !Ref GalleryDBSubnetGroup
      Engine: postgres
      EngineVersion: 12.3
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
  GalleryDBSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref ASubnetCIDR
      VpcId:
        Fn::ImportValue:
          !Sub ${NetworkName}Vpc
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
  GalleryDBSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref BSubnetCIDR
      VpcId:
        Fn::ImportValue:
          !Sub ${NetworkName}Vpc
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
  GalleryDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Includes subnets to use for Gallery DB
      DBSubnetGroupName: GalleryDBSUbnetGroup
      SubnetIds:
        - !Ref GalleryDBSubnetA
        - !Ref GalleryDBSubnetB


