debug: true
spring:
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://${db.host}:5432/image_gallery"
    username: ${rds.username}
    password: ${rds.password}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
amazon:
  s3:
    bucket-name: aws-image-gallery
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_ACCESS_KEY_ID}
  sns:
    topicArn: arn:aws:sns:eu-central-1:759046257668:S3UploadNotification_aws-image-gallery
    topicName: S3UploadNotification_${amazon.s3.bucket-name}
